spring:
  application:
    name: feign-consumer
server:
  port: 7004
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9102/eureka/
      
feign:
  hystrix:
    enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000